#!/bin/bash

if ! test -e kernel.allocation_funcs || ! test -e kernel.gfp_flags ; then
    echo "We need the kernel.allocation_funcs and the kernel.gfp_flags files"
    echo "The scripts to generate them are in smatch_data/"
    exit 1
fi

echo "// Automatically generated by add_gfp_to_allocations.sh" > kernel.allocation_funcs_gfp
for i in $(grep -v "//" kernel.allocation_funcs) ; do
    if ! grep -w $i kernel.gfp_flags ; then
	echo $i X
    fi
done >> kernel.allocation_funcs_gfp

echo "Done.  Created kernel.allocation_funcs_gfp"