#!/bin/bash

file=$1

if [[ "$file" = "" ]] ; then
    echo "Usage:  $0 <file with smatch messages>"
    exit 1
fi

new_file=kernel.array_bounds
bin_dir=$(dirname $0)
remove=$(echo ${bin_dir}/../smatch_data/kernel.array_bounds.remove)
tmp=$(mktemp /tmp/smatch.XXXX)

echo "// the format is: function <param> <max in array>" > $new_file
echo '// generated by `gen_puts_list.sh`' >> $new_file
grep "array index" $file | sed -e  's/(.*)//' | cut -d ' ' -f 3,6,10 | \
    perl -ne 'if ($_ =~ /\w+ \d+ \d+/) {print "$_\n"}' | \
    sort -u > $tmp
cat $tmp $remove $remove 2> /dev/null | sort | uniq -u >> $new_file
rm $tmp
echo "Done.  List saved as '$new_file'"

