#!/bin/bash

file=$1

if [[ "$file" = "" ]] ; then
    echo "Usage:  $0 <file with smatch messages>"
    exit 1
fi

echo "// list of functions and the argument they free." > kernel.frees_argument
echo '// generated by `gen_frees_list.sh`' >> kernel.frees_argument
grep -w free_arg $file | cut -d ' ' -f 3- >> kernel.frees_argument
echo "Done.  List saved as 'kernel.frees_argument'"

