#!/bin/bash

file=$1

if [[ "$file" = "" ]] ; then
    echo "Usage:  $0 <file with smatch messages>"
    exit 1
fi

outfile="kernel.no_le16"
bin_dir=$(dirname $0)
remove=$(echo ${bin_dir}/../smatch_data/${outfile}.remove)
tmp=$(mktemp /tmp/smatch.XXXX)
tmp2=$(mktemp /tmp/smatch.XXXX)

echo "// list of parameters where you don't need to call cpu_to_le16." > $outfile
echo '// generated by `gen_no_le16.sh`' >> $outfile

${bin_dir}/trace_params.pl $file usb_control_msg 4 >> $tmp
${bin_dir}/trace_params.pl $file usb_control_msg 5 >> $tmp
${bin_dir}/trace_params.pl $file usb_control_msg 7 >> $tmp

cat $tmp | sort -u > $tmp2
mv $tmp2 $tmp
cat $tmp $remove $remove 2> /dev/null | sort | uniq -u >> $outfile
rm $tmp
echo "Done.  List saved as '$outfile'"
