#!/bin/bash

function useage {
    echo "Usage:  $0 [--sparse][--valgrind][--debug] path/to/file.c"
    exit 1
}

CMD=smatch

while true ; do
    if [[ "$1" == "--sparse" ]] ; then
	CMD="sparse"
	shift
    elif [[ "$1" == "--valgrind" ]] ; then
	PRE="valgrind"
	shift
    elif [[ "$1" == "" ]] ; then
	break
    else
	if [[ "$1" == "--help" ]] ; then
		$CMD --help
		exit 1
	fi
	if echo $1 | grep -q ^- ; then
		POST="$POST $1"
	else
		break
	fi
	shift
    fi
done

cname=$1
cname=$(echo ${cname/.o/.c})
if [[ "$cname" == "" ]] ; then
    useage
fi
if ! test -e $cname ; then
    useage
fi

oname=$(echo ${cname/.c/.o})
rm -f $oname
make C=y CHECK="$PRE $CMD $POST" $oname
